
# This is a basic workflow to help you get started with Actions

name: my-telegram-bot-messenger

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          TELEGRAM_ACCESS_TOKEN="5225204796:AAHMkjKusf39iYD5TSToAtspifRQsl0p_4M"
          TELEGRAM_CHAT_ID="711263195"
          thoughts="
          thought1
          thought2
          thought3
          "
          while [[ -z $text ]] ; do
            text=$(echo "$thoughts" | shuf  -n1 | grep '.')
          done
          echo $text is: $text
          curl -X POST \
            -H "Content-Type: application/json" \
            -d @<(cat <<EOF 
          { "chat_id": "$TELEGRAM_CHAT_ID", "text": "$text", "parse_mode": "HTML" }
          EOF) \
            "https://api.telegram.org/bot$TELEGRAM_ACCESS_TOKEN/sendMessage"
